web_project/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.QuestionView.as_view(), name='question'),

    # ex: /polls/5/
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/', views.detail, name='detail'),

    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('about/', views.about, name='about'),
    path('contact', views.contact, name='contact'),

]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', views.index, name='index'),
    path('winter_winnpy/', views.winter_winnpy, name='winter_winnpy'),
    path('winter_univer/', views.winter_univer, name='winter_univer'),
    path('face_recognition/', views.face_recognition, name='face_recognition'),
]

urlpatterns += staticfiles_urlpatterns()

web_project/polls/models.py
from django.db import models

import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return (now - datetime.timedelta(days=1)) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def was_published_today(self):
        return self.pub_date.date() == datetime.date.today()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

web_project/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

def index(request):
    return render(request, 'polls/index.html')

def winter_winnpy(request):
    return redirect('http://winterai.herokuapp.com')

def winter_univer(request):
    return redirect('http://winnpysoft.pythonanywhere.com')

def face_recognition(request):
    return redirect('http://winter-x-face.herokuapp.com')

def about(request):
    return render(request, 'polls/about.html')

def contact(request):
    return render(request, 'polls/contact.html')

# def question(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))
class QuestionView(generic.ListView):
    template_name = 'polls/question.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not include those set to be
        publised in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'

#     def get_queryset(self):
#         """
#         Excludes any questions that aren't published yet.
#         """
#         return Question.objects.filter(pub_date__lte=timezone.now())
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id, pub_date__lte=timezone.now())
    
    choices = question.choice_set.all()
    
    # next_q = Question.objects.filter(pub_date__gt=question.pub_date).order_by('pub_date').first()
    # prev_q = Question.objects.filter(pub_date__lt=question.pub_date).order_by('pub_date').first()
    
    try:
        prev_q = question.get_previous_by_pub_date(pub_date__lte=timezone.now())
        prev_id = prev_q.id
    except:
        prev_id = 0

    try:
        next_q = question.get_next_by_pub_date(pub_date__lte=timezone.now())
        next_id = next_q.id
    except:
        next_id = 0
    
    context = {
            'question': question,
            'choices': choices,
            'prev_id': prev_id,
            'next_id': next_id
        }
    
    return render(request, 'polls/detail.html', context)


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Return the last five published questions (not include those set to be
        publised in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

web_project/polls/templates/polls/about.html
{% extends "polls/layout_general.html" %}
{% block title %}
About us
{% endblock %}
{% block content %}
<p>About page for the Visual Studio Code Django tutorial.</p>
{% endblock %}

web_project/polls/templates/polls/contact.html
{% extends "polls/layout_general.html" %}
{% block title %}
Contact us
{% endblock %}
{% block content %}
<p>Contact page for the Visual Studio Code Django tutorial.</p>
{% endblock %}

web_project/polls/templates/polls/detail.html
{% extends "polls/layout_general.html" %}
{% block title %}
Detail Page
{% endblock %}

{% block content %}
<h2>{{ question.question_text }}</h2>

{% if error_message %}
<p class='warning'><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

{% if prev_id %}
<p><a href="{% url 'polls:detail' prev_id %}">Previous question</a></p>
{% endif %}

{% if next_id %}
<p><a href="{% url 'polls:detail' next_id %}">Next question</a></p>
{% endif %}

</p>
<p><a href="{% url 'polls:question' %}">Back to questions (latest five)</a></p>
{% endblock %}

web_project/polls/templates/polls/index.html
{% extends "polls/layout_general.html" %}
{% block title %}
Home
{% endblock %}

{% block content %}
<h2>Select an app to run:</h2>
<ul>
    <li><a href="polls/">Polls app site (Python + Django + Sqlite3)</a></li>
    <li><a href="admin/">Polls admin site</a></li>
</ul>
<h2>Select a sister website to browse:</h2>
<ul>
    <li><a href="winter_winnpy/">Winter WinnPy (React + Node + Firebase + OAuth)</a></li>
    <li><a href="winter_univer/">Winter's Website (Python + Flask)</a></li>
    <li><a href="face_recognition/">Smart Face Recognition (React + Node + PostgreSQL)</a></li>
</ul>
{% endblock %}

web_project/polls/templates/polls/layout_general.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/polls_style.css' %}">
</head>

<body>
    <div class="navbar">
        <a href="{% url 'index' %}" class="navbar-brand">Home</a>
        <a href="{% url 'polls:about' %}" class="navbar-item">About</a>
        <a href="{% url 'polls:contact' %}" class="navbar-item">Contact</a>
    </div>

    <div class="body-content">
        {% block content %}
        {% endblock %}
        <hr />
        <footer>
            <p>© Winter WinnPy 2020</p>
        </footer>
    </div>
</body>

</html>

web_project/polls/templates/polls/question.html
{% extends "polls/layout_general.html" %}
{% block title %}
Questions
{% endblock %}

{% block content %}
{% if latest_question_list %}
<h1>Click on a question to vote:</h1>
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

web_project/polls/templates/polls/results.html
{% extends "polls/layout_general.html" %}
{% block title %}
Results
{% endblock %}

{% block content %}
<h3>{{ question.question_text }}</h3>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a><br>
<a href="{% url 'polls:question' %}">Back to questions</a>
{% endblock %}